# ===== email-service (CONSUMER) =====
spring.application.name=email-service

# Khong co REST API -> khong can web server
spring.main.web-application-type=none

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Consumer Group ID: moi service co group RIENG.
# 3 group khac nhau -> Kafka gui MOI message cho CA 3 service (fan-out).
spring.kafka.consumer.group-id=email-service-group

logging.level.com.demo.email=INFO
