# ===== audit-service (CONSUMER) =====
spring.application.name=audit-service
spring.main.web-application-type=none

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Group RIENG cua audit-service.
spring.kafka.consumer.group-id=audit-service-group

logging.level.com.demo.audit=INFO
