# ===== notification-service (CONSUMER) =====
spring.application.name=notification-service
spring.main.web-application-type=none

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Group RIENG cua notification-service -> nhan du moi message,
# doc lap voi email-service-group va audit-service-group.
spring.kafka.consumer.group-id=notification-service-group

logging.level.com.demo.notification=INFO
